name: PruebaModulo4-bucket 

on:
  pull_request:
    branches:
     -  main
jobs:
    VerificarCodigo:
      runs-on: ubuntu-latest

      steps:
        - name: obtener codigo
          uses: actions/checkout@v2

        - name: verificador si el codigo que esta 
          if: success()
          run: echo "El codigo se verifico con exito "

    DesplegarAWS:
      runs-on: ubuntu-latest
      needs: VerificarCodigo

      steps:
      - name: obtener codigo 
        uses: actions/checkout@v2

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v2 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: verificar s3
        run: aws s3 ls ${{secrets.AWS_S3_PATH}}


      - name: verificar estado de s3
        if: success()
        run: echo "S3 correcto "
        

      - name: Deploy application
        run: |
          aws s3 cp ./index.html ${{secrets.AWS_S3_PATH}}
          aws s3 cp ./error.html ${{secrets.AWS_S3_PATH}}
        
      - name: Subida de archivos
        if: success()
        run: echo " subida de archivos con exito "


      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"

      - name: Invalidacion realizada 
        if: success()
        run: echo " Realizacion de invalidacion con exito "
        

    






